[tool.ruff]
line-length = 119


[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 119
multi_line_output = 3
known_first_party = ["config"]

[tool.djlint]
profile = "django"
