# Generated by Django 4.2.17 on 2025-01-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_alter_review_body_alter_review_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="review.ticket",
            ),
        ),
    ]
